# Generated by Django 5.1 on 2024-11-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juizes',
            name='complement',
        ),
    ]
