# Generated by Django 5.1 on 2024-11-01 16:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juiz', '0002_remove_juizes_complement'),
    ]

    operations = [
        migrations.AddField(
            model_name='juizes',
            name='date2',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
